#!/usr/bin/env bash

set -e

script_dir=$(dirname "0")

cell_n="$(printf %02d $1)"
ex_n="$(printf %02d $2)"
assignment_dir="$script_dir/cell$cell_n/ex$ex_n"
assignment_file="$(ls $assignment_dir)"

session_name="Piscine-Evaluation"
tmux new-session -d -s "$session_name" -n "Evaluate-Cellule$1_$2" -c "$assignment_dir"
tmux split-window -v -t "$session_name" -c "$assignment_dir" -l 5
tmux send-keys -t "$session_name":1.1 "hx $assignment_file && tmux kill-session" Enter
tmux send-keys -t "$session_name":1.2 "clear" Enter
tmux select-pane -t "$session_name":1.1
tmux switchc -t "$session_name"
